### ISSUE TITLE
Is this still being developed?

### ISSUE THREAD

**Issue by jpnarkinsky** [mwmoeller/IHE-Node#5]
Just curious: is this still being developed?

**Comment by mwmoeller** [comment]
Not so much.  Interested in implementing some profiles?

**Comment by jpnarkinsky** [comment]
Possibly... we're a javascript shop so we'll have to make a decision
between implementing this in node or going with the Java reference
implementation.

--

*Patrick Narkinsky*patrick@narkinsky.com

**Comment by mwmoeller** [comment]
Sounds good.  If you go the node route, let me know.  Good luck!

**Comment by jpnarkinsky** [comment]
Can you give me a quick summary of the status?  Are any of the profiles usable?

**Comment by jpnarkinsky** [comment]
Definitely.  I'd guess we'll probably be getting to IHE stuff sometime in
April, but it's still an open goal.

--

*Patrick Narkinsky*patrick@narkinsky.com
